version: 2.1
executors:
  nodejs:
    docker:
      - image: circleci/node:10
jobs:
  build:
    executor: nodejs
    steps:
      - checkout
  notify:
    executor: nodejs
    steps:
      - run: echo "hello"
  

workflows:
  build_notify:
    jobs:
      - build
      - notify:
          requires:
            - build
      