version: 2.1
executors:
  nodejs:
    docker:
      - image: circleci/node:10
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    executor: nodejs
    steps:
      - checkout
  notify:
    executor: nodejs
    parameters:
      slackChannel:
        type: string
        default: circleci-prod-deployments-public
    steps:
      - run: echo << parameters.slackChannel >>
  
workflows:
  build_notify:
    jobs:
      - build
      - notify:
          slackChannel: test
          requires:
            - build
      