jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - slack/notify:
          channel: circleci-staging-deployments-private
          color: '#42e2f4'
          mentions: 'PraveenK'
          message: This is a custom message notification
          webhook: ${SLACK_WEBHOOK_URL}
      - slack/status:
          channel: circleci-prod-deployments-public
          fail_only: false
          mentions: 'praveen.kuninti'
          success_message: "The staging deployment is success"
          webhook: ${SLACK_WEBHOOK_URL}
orbs:
  slack: circleci/slack@3.4.2
version: 2.1
workflows:
  your-workflow:
    jobs:
      - build:
         context: slack