version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run: echo "hello world" 
      - run: env
      - checkout
  notify:
    docker:
      - image: circleci/node:10
    steps:
      - slack/status:
          channel: circleci-prod-deployments-public
          fail_only: false
          mentions: 'praveenk'
          success_message: Staging deployment successful for commit $CIRCLE_SHA1 and pull request $CIRCLE_PULL_REQUESTS
          webhook: ${SLACK_WEBHOOK_URL}
orbs:
  slack: circleci/slack@3.4.2

workflows:
  your-workflow:
    jobs:
      - build
      - notify:
          requires:
            - build
          context: slack
