jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run: echo "hello world" 
  notify:
    docker:
      - image: circleci/node:10
    steps:
      - slack/status:
          channel: circleci-prod-deployments-public
          fail_only: false
          mentions: 'praveen.kuninti'
          success_message: ':tada: Staging deployment successfule for pull request $CIRCLE_PULL_REQUEST'
          webhook: ${SLACK_WEBHOOK_URL}
orbs:
  slack: circleci/slack@3.4.2
version: 2.1
workflows:
  your-workflow:
    jobs:
      - build
      - notify:
         context: slack
