version: 2.1
executors:
  nodejs:
    docker:
      - image: circleci/node:10
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    executor: nodejs
    steps:
      - checkout
  notify:
    executor: nodejs
    parameters:
      slackChannel:
        type: string
        default: circleci-prod-deployments-public
    steps:
      - run: 
          name: Export local values
          command: echo "export COMMIT_ID=1234" >> $BASH_ENV; source $BASH_ENV
      - run: env
      - slack/status:
          channel: << parameters.slackChannel >>
          fail_only: false
          mentions: 'praveenk'
          success_message: Staging deployment successful for commit $COMMIT_ID
          webhook: ${SLACK_WEBHOOK_URL}
  
workflows:
  build_notify:
    jobs:
      - build
      - notify:
          slackChannel: circleci-staging-deployments-private
          context: slack
          requires:
            - build
      